server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL:jdbc:h2:mem:authdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "${OAUTH2_REDIRECT_URI:http://localhost:8081/login/oauth2/code/google}"
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_URL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Service Discovery (Eureka)
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      register-with-eureka: ${EUREKA_REGISTER:true}
      fetch-registry: ${EUREKA_FETCH:true}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

# Frontend and Backend URLs for CORS and Redirects
frontend-url: ${FRONTEND_URL:http://localhost:4200}
backend-url: ${BACKEND_URL:http://localhost:8081}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: auth-service
    description: Authentication service for QuickBite
    version: 1.0.0
