version: "3.8"

services:
  # =========================================================
  # INFRASTRUCTURE
  # =========================================================
  mysql:
    image: mysql:8.0
    container_name: quickbite-mysql
    restart: always
    cpus: 1.0
    mem_limit: 1024m
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - quickbite-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: quickbite-rabbitmq
    restart: always
    cpus: 0.5
    mem_limit: 512m
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - quickbite-network

  eureka-server:
    image: avinashkumar269/eureka-server:latest
    container_name: eureka-server
    restart: always
    cpus: 0.25
    mem_limit: 256m
    build:
      context: ./eureka-server
    environment:
      EUREKA_HOST: eureka-server
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - quickbite-network

  # =========================================================
  # GATEWAY & ADMIN
  # =========================================================
  admin-server:
    image: avinashkumar269/admin-server:latest
    container_name: admin-server
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./admin-server
    environment:
      PORT: 9090
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "9090:9090"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - quickbite-network

  api-gateway:
    image: avinashkumar269/api-gateway:latest
    container_name: api-gateway
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./api-gateway
    environment:
      SPRING_BOOT_ADMIN_MONITOR_TIMEOUT: 20000ms # Increase to 20 seconds
      SPRING_BOOT_ADMIN_MONITOR_CONNECT_TIMEOUT: 10000ms
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - quickbite-network

  # =========================================================
  # CORE MICROSERVICES
  # =========================================================
  auth-service:
    image: avinashkumar269/auth-service:latest
    container_name: auth-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./auth-service
    environment:
      PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/authdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      OAUTH2_REDIRECT_URI: ${OAUTH2_REDIRECT_URI}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      FRONTEND_URL: ${FRONTEND_URL}
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  restaurant-service:
    image: avinashkumar269/restaurant-service:latest
    container_name: restaurant-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./restaurant-service
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/restaurantdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      FRONTEND_URL: ${FRONTEND_URL}
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  menu-service:
    image: avinashkumar269/menu-service:latest
    container_name: menu-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./menu-service
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/menudb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  cart-service:
    image: avinashkumar269/cart-service:latest
    container_name: cart-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./cart-service
    environment:
      SERVER_PORT: 8084
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/cartdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  order-service:
    image: avinashkumar269/order-service:latest
    container_name: order-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./order-service
    environment:
      SERVER_PORT: 8085
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/orderdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      CART_SERVICE_URL: http://cart-service:8084
      PAYMENT_SERVICE_URL: http://payment-service:8086
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  payment-service:
    image: avinashkumar269/payment-service:latest
    container_name: payment-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./payment-service
    environment:
      SERVER_PORT: 8086
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/paymentdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}
      RAZORPAY_WEBHOOK_SECRET: ${RAZORPAY_WEBHOOK_SECRET}
      ORDER_SERVICE_BASE_URL: http://order-service:8085
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  delivery-service:
    image: avinashkumar269/delivery-service:latest
    container_name: delivery-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./delivery-service
    environment:
      PORT: 8087
      SPRING_CLOUD_COMPATIBILITY-VERIFIER_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/deliverydb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  notification-service:
    image: avinashkumar269/notification-service:latest
    container_name: notification-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./notification-service
    environment:
      PORT: 8088
      SPRING_CLOUD_COMPATIBILITY-VERIFIER_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/notificationdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_AUTH: ${SMTP_AUTH}
      SMTP_STARTTLS: ${SMTP_STARTTLS}
      SMS_PROVIDER: ${SMS_PROVIDER}
      SMS_GATEWAY_ENDPOINT: ${SMS_GATEWAY_ENDPOINT}
      SMS_GATEWAY_API_KEY: ${SMS_GATEWAY_API_KEY}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

  review-service:
    image: avinashkumar269/review-service:latest
    container_name: review-service
    restart: always
    cpus: 0.5
    mem_limit: 512m
    build:
      context: ./review-service
    environment:
      PORT: 8089
      SPRING_CLOUD_COMPATIBILITY-VERIFIER_ENABLED: "false"
      SPRING_DATASOURCE_URL: jdbc:mysql://quickbite-mysql:3306/reviewdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: quickbite-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JAVA_TOOL_OPTIONS: >
        -Xms128m -Xmx256m -XX:+UseSerialGC
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      eureka-server:
        condition: service_started
    networks:
      - quickbite-network

networks:
  quickbite-network:
    driver: bridge

volumes:
  mysql_data:
