spring:
  application:
    name: api-gateway

server:
  port: 8080

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${FRONTEND_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/oauth2/**,/login/**

        - id: quantity-service
          uri: lb://QUANTITY-SERVICE
          predicates:
            - Path=/api/**
          filters:
            - AuthenticationFilter

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    gateway:
      access: unrestricted