server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: payment-service
  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
        concurrency: ${RABBITMQ_LISTENER_CONCURRENCY:2}
        max-concurrency: ${RABBITMQ_LISTENER_MAX_CONCURRENCY:6}
        prefetch: ${RABBITMQ_LISTENER_PREFETCH:25}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

razorpay:
  key-id: ${RAZORPAY_KEY_ID:}
  key-secret: ${RAZORPAY_KEY_SECRET:}
  webhook-secret: ${RAZORPAY_WEBHOOK_SECRET:}

quickbite:
  order-service:
    base-url: ${ORDER_SERVICE_BASE_URL:http://localhost:8085}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
