version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: quickbite-menu-postgres
    environment:
      POSTGRES_DB: menu_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - menu-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: quickbite-menu-redis
    ports:
      - "6379:6379"

  jaeger:
    image: jaegertracing/all-in-one:1.54
    container_name: quickbite-menu-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  menu-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quickbite-menu-service
    depends_on:
      - postgres
      - redis
    environment:
      SERVER_PORT: 8083
      DB_URL: jdbc:postgresql://postgres:5432/menu_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: change-me-change-me-change-me-change-me
      EUREKA_REGISTER: "false"
      EUREKA_FETCH: "false"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    ports:
      - "8083:8083"

volumes:
  menu-postgres-data:
