spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:deliverydb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
