spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/reviewdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: review-service
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
        concurrency: ${RABBITMQ_LISTENER_CONCURRENCY:2}
        max-concurrency: ${RABBITMQ_LISTENER_MAX_CONCURRENCY:6}
        prefetch: ${RABBITMQ_LISTENER_PREFETCH:25}

server:
  port: ${PORT:8089}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: review-service:8089
  server:
    peer-node-read-timeout-ms: 20000
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

springdoc:
  packages-to-scan: com.quickbite.review.controller
  swagger-ui:
    path: /swagger-ui/index.html

quickbite:
  clients:
    order-service:
      name: order-service
      path: /orders
